### ISSUE TITLE
issue with pip install bytetrack on google collab

### ISSUE THREAD

**Issue by fenaux** [SkalskiP/yolov8-native-tracking#1]
Many thanks for your blogs and notebook.

I ran you notebook for track and count cars and trucks it works fine
I the tried to follow your blog  and replaced 
!git clone https://github.com/ifzhang/ByteTrack.git
with
!pip install bytetrack 

But I got an error message

Collecting bytetrack
  Using cached bytetrack-0.0.1.tar.gz (100 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: bytetrack
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for bytetrack (setup.py) ... error
  ERROR: Failed building wheel for bytetrack
  Running setup.py clean for bytetrack
Failed to build bytetrack
Installing collected packages: bytetrack
  error: subprocess-exited-with-error
  
  × Running setup.py install for bytetrack did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for bytetrack ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bytetrack

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

An idea how to fix it ?
Thanks for your help

**Comment by SkalskiP** [comment]
Hi @fenaux 👋🏻! Sorry for the late response. It is a separate project. We found some workaround to fix that problem.

```
!git clone https://github.com/ifzhang/ByteTrack.git
%cd ByteTrack

# workaround related to https://github.com/roboflow/notebooks/issues/80
!sed -i 's/onnx==1.8.1/onnx==1.9.0/g' requirements.txt
!pip3 install -q -r requirements.txt
```

I'm closing the issue. Feel free to reopen if you'll have more questions.
