### ISSUE TITLE
Custom trained model weights not being used in the yolov8 window

### ISSUE THREAD

**Issue by roobeshbalaji** [SkalskiP/yolov8-native-tracking#3]
I created a custom dataset and trained the yolov8 model to receive best.pt weights as shown in one of the youtube videos on the roboflow channel. when inserting the custom best.pt file in place of the yolov8n.pt file in the code the detections are not shown in the second window with the line counter. The detections are shown only in the first window and are not shown window with the line counter. the standard yolov8 model is unable to make any detections in my particular use case. When using the provided code without changing the weights file. Any detection made is displayed in both windows. Due to this, the line based counter is not working and I can't use the custom-trained model weights.

**Comment by roobeshbalaji** [comment]
After some back and forth with gpt, it seems that the object that I custom trained the model to detect has the detections.class_id of 0, which was being filtered out by a line mentioned in the code. Changing this line to "detections = detections[detections.class_id != 60]" solved the issue. This issue can be converted into a discussion so it can be helpful for someone with the same issue.

**Comment by SkalskiP** [comment]
Hi @roobeshbalaji 👋🏻! Great that you managed to solve your problem. Sorry for the late reply. I have been quite busy lately. 

I'm pretty sure that, in your case, you can remove that whole line.

```
detections = detections[detections.class_id != 60]
```
