### ISSUE TITLE
Tracker_ids return none when working with multiple sources

### ISSUE THREAD

**Issue by iremcorakk** [SkalskiP/yolov8-native-tracking#6]
I am working with 5 cameras in my project. When I frame a single camera, there is no problem, but when I try to track for 5 cameras, the tracker_ids return to none. What could this be about?

while True:
     for i in range(cam_no):
         ret[i], frame[i] = cap[i].read()

         for result in model.track(source=frame[i], show=True, stream=True, agnostic_nms=True):

             tracking_frame = result.orig_img
             detections = sv.Detections.from_yolov8(result)

             if result.boxes.id is not None:
                 detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)

             detections = detections[(detections.class_id != 60) & (detections.class_id != 0)]

             print("tracker id ",detections.tracker_id)
             ...
             ...

**Comment by SkalskiP** [comment]
Hi @iremcorakk 👋🏻 !

Sorry to hear that. This repo is just a usage example if you experience problems like that, I would reach out directly to the Ultralitics team and ask for fixing that issue. You can do it [here](https://github.com/ultralytics/ultralytics/issues).
